language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
env:
    global:
        - PHPUNIT_FLAGS="-v"
matrix:
    fast_finish: true
    include:
          # Minimum supported dependencies with the latest and oldest PHP version
          - php: 8.1
before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
script:
    - composer validate --strict --no-check-lock
    # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
    # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
    - ./vendor/bin/phpunit $PHPUNIT_FLAGS tests/Unit